export const storeConfig = {
  selectedStoreId: "omori",
  stores: [
    {
      id: "omori",
      name: "大森町店",
      distance: "831 m",
      address: "東京都大田区大森西 3-20-13",
      note: "最も近い店舗",
    },
    {
      id: "atre",
      name: "アトレ大森店",
      distance: "2.6 km",
      address: "東京都大田区大森北 1-6-16",
      note: "前回ご利用",
    },
  ],
};

export const menuConfig = {
  categories: [
    { id: "recommended", label: "おすすめ" },
    { id: "set", label: "セット" },
    { id: "single", label: "単品" },
    { id: "side", label: "サイドメニュー" },
    { id: "sweets", label: "スイーツ" },
    { id: "drink", label: "ドリンク" },
  ],
  items: [
    { id: "chicken-muffin-set", category: "recommended", name: "おすすめA", price: 650, badge: "おすすめ", hasDetail: true, components: ["単品A", "サイドA"] },
    { id: "blue-soda", category: "recommended", name: "おすすめB", price: 320, badge: "おすすめ", hasDetail: true, components: ["単品B", "サイドA"] },
    { id: "sausage-egg-set", category: "recommended", name: "おすすめC", price: 560, hasDetail: true, components: ["単品C", "サイドA"] },
    { id: "sausage-set", category: "set", name: "セットA", price: 450, hasDetail: true, components: ["単品A", "サイドA"] },
    { id: "egg-set", category: "set", name: "セットB", price: 490, hasDetail: true, components: ["単品B", "サイドA"] },
    { id: "teriyaki-set", category: "set", name: "セットC", price: 690, hasDetail: true, components: ["単品C", "サイドA"] },
    { id: "fish-set", category: "set", name: "セットD", price: 660, hasDetail: true, components: ["単品D", "サイドA"] },
    { id: "chicken-single", category: "single", name: "単品A", price: 390, hasDetail: true, itemType: "single", components: ["単品A"] },
    { id: "cheese-single", category: "single", name: "単品B", price: 240, hasDetail: true, itemType: "single", components: ["単品B"] },
    { id: "teriyaki-single", category: "single", name: "単品C", price: 430, hasDetail: true, itemType: "single", components: ["単品C"] },
    { id: "fish-single", category: "single", name: "単品D", price: 420, hasDetail: true, itemType: "single", components: ["単品D"] },
    { id: "hash-potato", category: "side", name: "サイドA", price: 180, hasDetail: true, itemType: "single", components: ["サイドA"] },
    { id: "french-fries", category: "side", name: "サイドB", price: 330, hasDetail: true, itemType: "single", components: ["サイドB"] },
    { id: "nuggets", category: "side", name: "サイドC", price: 260, hasDetail: true, itemType: "single", components: ["サイドC"] },
    { id: "side-salad", category: "side", name: "サイドD", price: 300, hasDetail: true, itemType: "single", components: ["サイドD"] },
    { id: "soft-cream", category: "sweets", name: "スイーツA", price: 190, hasDetail: true, itemType: "single", components: ["スイーツA"] },
    { id: "apple-pie", category: "sweets", name: "スイーツB", price: 180, hasDetail: true, itemType: "single", components: ["スイーツB"] },
    { id: "pancake", category: "sweets", name: "スイーツC", price: 250, hasDetail: true, itemType: "single", components: ["スイーツC"] },
    { id: "smoothie", category: "sweets", name: "スイーツD", price: 500, disabled: true, itemType: "single", components: ["スイーツD"] },
    { id: "cola-list", category: "drink", name: "ドリンクA", price: 150, hasDetail: true, itemType: "single", components: ["ドリンクA"] },
    { id: "sprite-list", category: "drink", name: "ドリンクB", price: 150, hasDetail: true, itemType: "single", components: ["ドリンクB"] },
    { id: "orange-list", category: "drink", name: "ドリンクC", price: 170, hasDetail: true, itemType: "single", components: ["ドリンクC"] },
    { id: "coffee-list", category: "drink", name: "ドリンクD", price: 160, hasDetail: true, itemType: "single", components: ["ドリンクD"] },
  ],
  drinks: [
    { id: "cola", name: "ドリンクA" },
    { id: "sprite", name: "ドリンクB" },
    { id: "orange", name: "ドリンクC" },
    { id: "zero", name: "ドリンクD" },
    { id: "grape", name: "ドリンクE" },
    { id: "melon", name: "ドリンクF" },
    { id: "tea", name: "ドリンクG" },
    { id: "coffee", name: "ドリンクH" },
    { id: "ice-tea", name: "ドリンクI" },
    { id: "vegetable", name: "ドリンクJ" },
  ],
};